Repository Ashutosh249/Hacktoberfest-Beginners, pull requests merged in 2021-10, with the labels that each got.

#6 Create SelectionSort.c
  SelectionSort.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#4 html form element
  form.html
Labels: hacktoberfest-accepted, hacktoberfest2021

#3 Create Linear_search.cpp
  Linear_search.cpp
Labels: hacktoberfest2021, hacktoberfestaccepted

#2 Update README.md
  README.md
Labels: duplicate, good first issue

#7 added stack/queue and binary search tree
  Linked_list.cpp
  StackQueueLL.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest2021

#23 Added Dijkstra Algorithm
  DIJIKSTRA.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#25 Create stackarray.c
  stackarray.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#22 Create Deletion.c
  Deletion.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#26 Create heapsort.c
  heapsort.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#28 Create MergeSort.c
  MergeSort.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2021, hacktoberfest-2021, hacktoberfestaccepted

#176 computed recursive factorial.
  recursiveFactorial.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#183 shortest job first
  sjf.c
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#182 Create SignedMul8bit.asm
  SignedMul8bit.asm
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#181 implementation of hashsort in cpp
  hashsort.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#180 Create selection-sort.py
  selection-sort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#179 merge sort listed using c++
  QuickSort on Doubly Linked List.cpp
  merge sort listed using c++.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#178 bit manipulation
  Adjacent Bit Count.cpp
  set_ith_bit.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021

#177 add DFS algorithm using java
  DFS.java
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest-2021
